language: node_js
node_js:
  - "lts/*"
script:
  - echo 'Installing dependencies'
  - npm install
  - echo "Running npm build"
  - npm run build
  - echo "Deploying Daily Ideas to Firebase"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project daily-ideas  --token $FIREBASE_TOKEN
